# Generated by Django 4.2 on 2023-05-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
