# Generated by Django 4.2 on 2023-05-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
