# Generated by Django 4.2 on 2023-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0004_remove_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField()),
                ('Gender', models.CharField()),
                ('Category', models.CharField()),
                ('SubCategory', models.CharField()),
                ('ProductType', models.CharField()),
                ('Colour', models.CharField()),
                ('Usage', models.CharField()),
                ('ProductTitle', models.CharField()),
                ('Image', models.ImageField(upload_to='')),
                ('ImageURL', models.CharField()),
            ],
        ),
    ]
